version: '3'
services:

  mongo:
    container_name: mongodb-custo-api-go
    image: mongo:4.2.0
    ports:
      - "27020:27017"


  app:
    build:
      context: .
      args:
        config: "./config/production.yml"
    container_name: app-custo-api-go
    image: "istore221/custo-api-go:1.0.0"
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=production #read from env ${APP_ENV}
    links:
      - mongo
